/**
 * Migration list — extracted from server.js for testability.
 *
 * Each entry: { slug, label }. slug must match the migration filename
 * under src/migrations/ (without .js). server.js loads each via
 * loadMigrationModule(); tests verify file existence, export shape, no
 * duplicates, monotonic IDs, and the post-100 postal_codes_served
 * contract (migration 100 is the source-of-truth boundary; later
 * migrations must not write postal_codes_served — ScrapeConfigSync owns
 * that column from then on).
 */

const path = require('path');

const MIGRATIONS_DIR = path.join(__dirname, 'migrations');

const migrations = [
  { slug: '006-activity-analytics', label: 'Activity analytics' },
  { slug: '008-add-device-id-tracking', label: 'Device ID tracking' },
  { slug: '009-add-waitlist', label: 'Waitlist' },
  { slug: '014-add-pwa-events', label: 'PWA events' },
  { slug: '015-add-tc-fuel-oil', label: 'TC Fuel Oil' },
  { slug: '016-add-tevis-energy', label: 'Tevis Energy' },
  { slug: '017-add-delaware-suppliers', label: 'Delaware suppliers' },
  { slug: '024-fix-abc-fuel-location', label: 'ABC Fuel location' },
  { slug: '025-add-sherman-ct-suppliers', label: 'Sherman CT suppliers' },
  { slug: '026-add-hometown-reliable-fuel', label: 'Hometown/Reliable' },
  { slug: '027-add-gaylordsville-suppliers', label: 'Gaylordsville suppliers' },
  { slug: '028-add-vernon-area-suppliers', label: 'Vernon area suppliers' },
  { slug: '029-add-portland-pa-suppliers', label: 'Portland PA suppliers' },
  { slug: '030-add-elizabethtown-pa-suppliers', label: 'Elizabethtown PA suppliers' },
  { slug: '031-add-york-pa-suppliers', label: 'York PA suppliers' },
  { slug: '032-add-dighton-ma-suppliers', label: 'Dighton MA suppliers' },
  { slug: '033-add-kent-county-de-suppliers', label: 'Kent County DE suppliers' },
  { slug: '034-add-western-ct-suppliers', label: 'Western CT suppliers' },
  { slug: '035-add-hudson-valley-ny-suppliers', label: 'Hudson Valley NY suppliers' },
  { slug: '036-add-sms-price-support', label: 'SMS price support' },
  { slug: '037-add-alaska-suppliers', label: 'Alaska suppliers' },
  { slug: '038-add-347-oil', label: '347 Oil' },
  { slug: '039-add-cod-suppliers', label: 'COD suppliers' },
  { slug: '040-add-jennison-fuels', label: 'Jennison Fuels' },
  { slug: '041-add-ace-fueling', label: 'Ace Fueling' },
  { slug: '042-add-regional-cod-suppliers', label: 'Regional COD suppliers' },
  { slug: '043-add-pa-regional-suppliers', label: 'PA regional suppliers' },
  { slug: '044-add-bangor-me-suppliers', label: 'Bangor ME suppliers' },
  { slug: '045-add-cn-brown-energy', label: 'CN Brown Energy' },
  { slug: '046-add-casco-me-suppliers', label: 'Casco ME suppliers' },
  { slug: '047-add-coverage-gap-suppliers', label: 'Coverage gap suppliers' },
  { slug: '048-add-ip-hash-to-user-locations', label: 'IP hash' },
  { slug: '049-add-cheshire-nh-suppliers', label: 'Cheshire NH suppliers' },
  { slug: '050-add-northern-nh-suppliers', label: 'Northern NH suppliers' },
  { slug: '051-add-fairfield-ct-suppliers', label: 'Fairfield CT suppliers' },
  { slug: '052-add-ct-coverage-suppliers', label: 'CT coverage suppliers' },
  { slug: '053-add-eastern-ct-suppliers', label: 'Eastern CT suppliers' },
  { slug: '054-add-ct-directory-suppliers', label: 'CT directory suppliers' },
  { slug: '055-add-ct-cod-suppliers', label: 'CT COD suppliers' },
  { slug: '056-add-delivery-model-column', label: 'Delivery model column' },
  { slug: '057-add-zip-price-stats-tables', label: 'ZIP price stats' },
  { slug: '058-add-zip-to-county-table', label: 'ZIP to County' },
  { slug: '059-cleanup-duplicate-suppliers', label: 'Duplicate cleanup' },
  { slug: '060-fix-expired-prices', label: 'Fix expired prices' },
  { slug: '061-add-dragon-fuel-llc', label: 'Dragon Fuel LLC' },
  { slug: '062-add-port-jervis-area-suppliers', label: 'Port Jervis area' },
  { slug: '063-add-quakertown-area-suppliers', label: 'Quakertown area' },
  { slug: '064-add-recovered-403-suppliers', label: 'Recovered 403 suppliers' },
  { slug: '065-add-metro-energy-boston', label: 'Metro Energy Boston' },
  { slug: '066-add-werley-energy', label: 'Werley Energy' },
  { slug: '067-enable-kelleys-oil', label: "Kelley's Oil" },
  { slug: '068-enable-seven-suppliers', label: 'Seven suppliers' },
  { slug: '069-fix-cooldown-suppliers', label: 'Cooldown fix' },
  { slug: '070-fix-stale-suppliers', label: 'Stale suppliers fix' },
  { slug: '071-fix-remaining-stale', label: 'Remaining stale fix' },
  { slug: '072-add-westchester-putnam-suppliers', label: 'Westchester/Putnam suppliers' },
  { slug: '073-cleanup-scrapeconfig-duplicates', label: 'ScrapeConfigSync duplicate cleanup' },
  { slug: '074-add-daily-platform-metrics', label: 'Daily platform metrics' },
  { slug: '075-supplier-data-integrity', label: 'Supplier data integrity' },
  { slug: '076-add-me-ct-incomplete-suppliers', label: 'ME/CT incomplete suppliers' },
  { slug: '077-add-ma-suppliers-batch1', label: 'MA suppliers batch 1' },
  { slug: '078-add-ma-suppliers-batch2', label: 'MA suppliers batch 2' },
  { slug: '079-add-ma-suppliers-batch3', label: 'MA suppliers batch 3' },
  { slug: '080-add-ri-suppliers', label: 'RI suppliers' },
  { slug: '081-add-nh-suppliers', label: 'NH suppliers' },
  { slug: '082-add-me-suppliers', label: 'ME suppliers' },
  { slug: '083-add-ct-suppliers', label: 'CT suppliers' },
  { slug: '084-add-vt-suppliers', label: 'VT suppliers' },
  { slug: '085-claim-unique-index', label: 'Claim unique index' },
  { slug: '086-claim-funnel-hardening', label: 'Claim funnel hardening' },
  { slug: '087-backfill-westchester-putnam-coverage', label: 'Backfill Westchester/Putnam coverage' },
  { slug: '088-backfill-de-md-coverage', label: 'Backfill DE/MD coverage' },
  { slug: '089-backfill-baltimore-coverage', label: 'Backfill Baltimore coverage' },
  { slug: '090-add-luzerne-carbon-schuylkill-suppliers', label: 'Luzerne/Carbon/Schuylkill PA suppliers' },
  { slug: '091-add-upstate-ny-suppliers', label: 'Upstate NY suppliers' },
  { slug: '092-add-northern-virginia-suppliers', label: 'Northern Virginia suppliers' },
  { slug: '093-fix-stale-price-display-flags', label: 'Fix stale price display flags' },
  { slug: '094-add-price-alert-subscribers', label: 'Price alert subscribers' },
  { slug: '095-merge-duplicate-suppliers', label: 'Merge duplicate suppliers' },
  { slug: '096-add-walker-valley-suppliers', label: 'Walker Valley area suppliers' },
  { slug: '097-add-staffordville-coverage', label: 'Staffordville coverage' },
  { slug: '098-backfill-limited-coverage-zips', label: 'Backfill limited-coverage ZIPs + Hilton Oil' },
  { slug: '099-fix-overwritten-coverage', label: 'Fix overwritten supplier coverage' },
  { slug: '100-scrapeconfig-coverage-authority', label: 'scrape-config coverage authority' },
  { slug: '101-add-northumberland-pa-suppliers', label: 'Northumberland PA suppliers' },
  { slug: '102-add-herkimer-ny-suppliers', label: 'Herkimer NY suppliers' },
  { slug: '103-create-user-events', label: 'User events tracking' },
  { slug: '104-add-utica-ny-suppliers', label: 'Utica NY suppliers' },
  { slug: '105-create-supplier-requests', label: 'Supplier requests table' },
  { slug: '106-price-review-enhancements', label: 'Price review enhancements' },
  { slug: '107-add-fawcett-energy-ma', label: 'Fawcett Energy MA' },
  { slug: '108-add-fulton-ny-suppliers', label: 'Fulton NY / Oswego County suppliers' },
  { slug: '109-add-dansville-ny-suppliers', label: 'Dansville NY / Livingston County suppliers' },
  { slug: '110-add-kerosene-fuel-type', label: 'Add kerosene fuel type' },
  { slug: '111-fix-price-alert-last-seen', label: 'Fix price alert first-send bug' },
  { slug: '112-add-central-pa-suppliers', label: 'Central PA suppliers (Dolan Oil, Talley Petroleum)' },
  { slug: '113-reset-jsonld-blocked-suppliers', label: 'Reset 40 blocked suppliers (fix monthlyReset failure dates bug)' },
  { slug: '114-reset-config-fix-suppliers', label: 'Reset 5 suppliers (config fixes + slug corrections)' },
  { slug: '115-reset-stale-regex-suppliers', label: 'Reset 3 suppliers (stale regex + Hometown Fuel json_api)' },
  { slug: '116-reset-unclear-suppliers', label: 'Reset 3 suppliers (Premier Energy + Fettinger + Hollenbach)' },
  { slug: '117-reset-wix-fixable-suppliers', label: 'Reset 3 suppliers (Higgins + Red Star + Kelleys — HTML entity regex fixes)' },
  { slug: '118-add-queens-college-point-supplier', label: "Angelo's Fuel Oil Co (Queens/College Point)" },
  { slug: '119-add-supplier-active-index', label: 'Add partial index on suppliers.active for query performance' },
  { slug: '120-dashboard-indexes', label: 'Dashboard composite indexes' },
  { slug: '121-add-nashua-nh-suppliers', label: 'Shattuck Oil + Absco Heating (Nashua NH area)' },
  { slug: '122-add-susquehanna-pa-suppliers', label: 'Windswept + Economy Heating (Susquehanna PA / Southern Tier NY)' },
  { slug: '123-add-morgan-oil-virginia', label: 'Morgan Oil Corporation (Marshall, VA — Loudoun/Fauquier 5-county)' },
  { slug: '124-add-do-not-pitch-flag', label: 'Add do_not_pitch column to suppliers' },
  { slug: '125-add-droplet-suppliers', label: 'Droplet Fuel: 19 new suppliers + do_not_pitch flag on 30 Droplet suppliers' },
  { slug: '126-add-cron-heartbeats', label: 'Cron heartbeats + error log tables (Phase 2 automation)' },
  { slug: '127-reset-stale-audit-suppliers', label: 'Reset backoff for 5 stale-audit suppliers' },
  { slug: '128-add-sunrise-heating-stamford', label: 'Sunrise Heating Fuels (Stamford NY — Delaware/Schoharie/Greene/Otsego)' },
  { slug: '129-add-jk-sons-fuel-margaretville', label: 'JK & Sons Fuel Oil (Margaretville NY — Delaware/6-county)' },
  { slug: '130-add-hancock-md-suppliers', label: 'Steffey & Findlay + Brothers Heating Oil (Hancock/Hagerstown MD)' },
  { slug: '131-add-woodruff-energy-bridgeton', label: 'Woodruff Energy (Bridgeton NJ — 6-county South Jersey)' },
  { slug: '132-add-patriot-discount-oil-nj', label: 'Patriot Discount Oil (Whitehouse NJ — Hunterdon/Warren/Somerset/Morris)' },
  { slug: '133-create-coverage-requests', label: 'Coverage requests table (empty ZIP email notifications)' },
  { slug: '134-create-quote-requests', label: 'Quote requests + supplier junction tables (heatingoil-h1fy)' },
  { slug: '135-add-supplier-lead-columns', label: 'Supplier lead opt-in columns (heatingoil-h1fy)' },
  { slug: '136-add-scrape-runs-rejections', label: 'Scrape runs rejections column (outlier detection)' },
  { slug: '137-add-atlas-oil-new-berlinville', label: 'Atlas Oil (New Berlinville PA) + activate Clayton Discount Fuel (Langhorne PA)' },
  { slug: '138-add-l-and-son-heat-yonkers', label: 'L & Son Heat/AC Tech (Yonkers NY)' },
  { slug: '139-add-thomson-fuels-bradford-vt', label: 'Thomson Fuels (Bradford VT)' },
  { slug: '140-add-asi-oil-norwich-ct', label: 'ASI Oil (Norwich CT — New London County)' },
  { slug: '141-add-user-mention-suppliers', label: 'User-mention batch: Castle Fuel NY, Costello PA, F.C. Haab PA, Victory PA, Fortified Fuels CT + L&Son aliases' },
  { slug: '142-add-wargo-coal-oil', label: 'Wargo Coal & Oil Inc (McAdoo PA — Greater Hazleton, Luzerne/Schuylkill/Carbon)' },
  { slug: '143-add-incorporation-fields', label: 'Incorporation fields + NY/CT filing dates for 30 suppliers (outreach correlation)' },
  { slug: '144-add-fegley-oil', label: 'Fegley Oil Company (Tamaqua PA — Schuylkill/Carbon/Luzerne counties)' },
  { slug: '145-add-propane-fuel-type', label: 'Add propane to fuel_type ENUMs (supplier_prices + community_deliveries)' },
  { slug: '146-add-augusta-me-suppliers', label: 'Augusta ME (04330) gap: Litchfield Fuel + M.A. Haskell + CN Brown Augusta' },
  { slug: '147-add-jc-heating-cooling', label: 'JC Heating & Cooling (Levittown/Yardley PA — Bucks/Montgomery 40 towns)' },
  { slug: '148-add-leroux-fuels-ny', label: 'Leroux Fuels (Plattsburgh NY — Clinton + N. Essex counties)' },
  { slug: '149-add-energy-coop-vermont', label: 'Energy Co-op of Vermont (Colchester VT — Chittenden+4 counties)' },
  { slug: '150-add-hudson-fuel-oil-oh', label: 'Hudson Fuel Oil (New Richmond OH — Cincinnati metro, 3rd in-state OH supplier)' },
  { slug: '151-add-jackman-fuels-vt', label: 'Jackman Fuels Inc (Vergennes VT — Addison+Chittenden counties, will-call)' },
  { slug: '152-add-cn-brown-lancaster', label: 'CN Brown Energy (Lancaster NH — NEK VT + Coos NH, 3rd CN Brown branch via multi-branch config)' },
  { slug: '153-add-central-pa-suppliers', label: 'Central PA gap fill (Lewistown 17044): Nittany Energy (Lewistown), Snedeker Energy, J.J. Powell (Lewistown), Oakland Fuel Oil (Mifflintown/Juniata)' },
  { slug: '154-add-dixieland-energy', label: 'Dixie Land Energy (Rising Sun MD — Cecil/Harford MD + New Castle DE + Chester/Lancaster/York PA, will-call confirmed, no scrapable price)' },
  { slug: '155-add-coverage-requests-notified-fuels', label: 'Per-fuel notification tracking on coverage_requests (notified_fuels text[] + index swap)' },
  { slug: '156-add-buxton-multi-fuel-types', label: 'Buxton Oil fuel_types: oil → heating_oil+propane+kerosene (paired with primaryFuelOptional config flag)' },
  { slug: '157-add-warren-county-ny-suppliers', label: 'Warren County NY (12815 gap fill): Long Energy (Schenectady — Capital Region + Warren) + Mountain Petroleum (Schroon Lake — Adirondacks)' },
  { slug: '158-add-rj-waterhouse-fuel-oil', label: 'RJ Waterhouse Fuel Oil (Lake Luzerne NY — Mirabito sub-brand acquired Sept 2025; Warren/Saratoga/Washington counties)' },
  { slug: '159-add-ron-bush-oil', label: 'Ron Bush Oil (LaFayette NY — Mirabito sub-brand acquired Aug 2025; 8-county central NY incl. Syracuse metro)' },
  { slug: '160-add-mountain-view-fuel', label: 'Mountain View Fuel (Bethel PA — Countryside Propane LLC dba; Berks/Lebanon/Lancaster/Dauphin; heating oil + kerosene + propane, will-call/On-Call confirmed, no scrapable price)' },
  { slug: '161-add-countryside-fuels', label: 'Countryside Fuels (Fultonville NY — Gramuglia family since 1975, 3 depots, 10 NY counties: Fulton/Herkimer/Montgomery/Schenectady/Schoharie/Clinton/Essex/Chenango/Delaware/Otsego; heating oil + kerosene, published per-location prices)' },
  { slug: '162-add-warfordsburg-region-suppliers', label: 'Warfordsburg PA 17267 gap fill: C.M. Fuels (Spring Run PA, 4 counties Franklin/Juniata/Fulton/Huntingdon, scrapable HO+kerosene), McCleary Oil (Chambersburg PA Franklin Co, call-in, no scrape), Roach Energy (Martinsburg WV — Washington Co MD coverage only, will-call, no scrape)' },
  { slug: '163-fix-suppliers-fuel-types-default', label: 'Flip suppliers.fuel_types DEFAULT from ["oil"] → ["heating_oil"] so ScrapeConfigSync INSERTs no longer leak legacy tag (heatingoil-qeix, blocks kz7j backfill)' },
  { slug: '164-add-wardwell-no-frills-blue-hill', label: 'Wardwell Oil (Sedgwick ME) + No Frills Oil (Hancock ME) — Blue Hill peninsula / Hancock County COD; closes 04614 gap; same parent (No Frills Oil Co., Inc.) operating two brands with distinct prices' },
  { slug: '165-rehabilitate-cn-brown-brewer', label: 'Rehabilitate orphan cn-brown-energy → cn-brown-brewer (Brewer ME, 10 Penobscot ZIPs $4.799). Repoints website cnbrown.com → cnbrownenergy.com, scopes coverage to live Brewer-routed ZIPs, drops propane. Pittsfield + Mattawamkeag branches filed as follow-ups' },
  { slug: '166-add-cn-brown-pittsfield-mattawamkeag', label: 'CN Brown Energy (Pittsfield) — 12 ZIPs Penobscot/Somerset + (Mattawamkeag) — 5 remote Penobscot ZIPs. Both branches discovered during mig 165 orphan rehab; both already active CN Brown offices on cnbrownenergy.com lookup. Closes heatingoil-7r8b + heatingoil-ijuu' },
  { slug: '167-delete-cn-brown-energy-orphan', label: 'Idempotent DELETE for cn-brown-energy orphan row that mig 045 resurrected at 14:32 UTC 2026-05-13. Runs every boot as backstop in case mig 045 misfires again; companion change moves cnbrown.com to scrape-config _ignore_list' },
  { slug: '168-add-pa-md-suppliers-batch', label: 'PA + MD supplier batch (2 new): Shaffer Oil (Somerset/Cambria PA, will-call, no scrape); SJ Johnson (Huntingtown MD, COD/will-call/no-contract, scrapable $4.699). Best Price Oil + Tevis Energy were already in production (migs 031/016/089) with reduced coverage; expanding their footprint left for a sibling task. Companion: 8 new ZIPs in zip-database.json (3 PA Wellersburg-area + 5 MD SJ Johnson hamlets)' },
  { slug: '169-fix-mig168-service-cities', label: 'Fix mig 168 serviceCities under-coverage: Shaffer Oil 18→65 cities (adds Wellersburg + West Salisbury + 45 other Somerset/Cambria towns); SJ Johnson 20→43 cities (adds Indian Head/Marbury/Chaptico + 20 other St.Marys/Calvert/Charles towns). serviceCities drives supplierMatcher city-tier ranking + supplier profile page town listings + iOS bundled directory — not cosmetic.' },
  { slug: '170-backfill-service-cities-bulk', label: 'Bulk backfill service_cities for 201 suppliers <90% city-coverage (heatingoil-0nnk audit): 4,194 net city additions across the entire flagged cohort. Additive union (existing + zip-db expansion), cannot shrink any supplier. Worst expansions: fawcett-energy 76→296, long-energy 20→209, countryside-fuels 3→187. Data baked from prod DB snapshot 2026-05-16.' },
  { slug: '171-add-primary-fuel-optional-to-suppliers', label: 'Add suppliers.primary_fuel_optional BOOLEAN column (Cluster A foundation, heatingoil-kjnt). Backfills Buxton (only current user). ScrapeConfigSync writes the column from scrape-config primaryFuelOptional on each boot (single-branch entries only; branches use per-branch migration per existing _syncSupplierCoverage contract).' },
  { slug: '172-backfill-fuel-types-oil-to-heating-oil', label: 'Backfill suppliers.fuel_types — normalize legacy "oil" → canonical "heating_oil" across 417 rows (heatingoil-kz7j). Element-wise jsonb_agg swap preserves mixed tags (e.g. ["oil","kerosene"] → ["heating_oil","kerosene"]). Companion to migration 163 (qeix) which flipped the column DEFAULT. Idempotent. Safe per 2026-05-05 audit (iOS DirectorySupplier drops unknown keys; routes have OR-fallback for both forms).' },
];

function loadMigrationModule(m) {
  return require(path.join(MIGRATIONS_DIR, m.slug));
}

function migrationId(m) {
  const num = String(m.slug).match(/^(\d+)/);
  return num ? parseInt(num[1], 10) : null;
}

module.exports = { migrations, loadMigrationModule, migrationId, MIGRATIONS_DIR };
